* removed separate configuration for plugins * improved altivec runtime detection (niklas werner)
git-svn-id: https://supercollider.svn.sourceforge.net/svnroot/supercollider/trunk@2724 a380766d-ff14-0410-b294-a243070f3f08

diff --git a/linux/bootstrap b/linux/bootstrap
--- a/linux/bootstrap
+++ b/linux/bootstrap
@@ -24,24 +24,26 @@ do_bootstrap()
     set +x
 }
 
-case "$1" in
-    server|lang)
-	echo "* bootstrapping server/lang"
-	do_bootstrap
-	;;
-    plugins)
-	if test -d source/plugins; then
-	    echo "* bootstrapping plugins"
-	    cd source/plugins && do_bootstrap
-	else
-	    echo "directory source/plugins not found"
-	    exit 1
-	fi
-	;;
-    *)
-	"$bootstrap" server
-	"$bootstrap" plugins
-	;;
-esac
+# case "$1" in
+#     server|lang)
+# 	echo "* bootstrapping server/lang"
+# 	do_bootstrap
+# 	;;
+#     plugins)
+# 	if test -d source/plugins; then
+# 	    echo "* bootstrapping plugins"
+# 	    cd source/plugins && do_bootstrap
+# 	else
+# 	    echo "directory source/plugins not found"
+# 	    exit 1
+# 	fi
+# 	;;
+#     *)
+# 	"$bootstrap" server
+# 	"$bootstrap" plugins
+# 	;;
+# esac
+
+do_bootstrap
 
 # EOF
