- added ALSA/MIDI implementation - added abstract class SC_LanguageClient - fixed method names in Main class extension
git-svn-id: https://supercollider.svn.sourceforge.net/svnroot/supercollider/trunk@2305 a380766d-ff14-0410-b294-a243070f3f08

diff --git a/linux/bootstrap b/linux/bootstrap
--- a/linux/bootstrap
+++ b/linux/bootstrap
@@ -6,19 +6,42 @@
 # CVS:		$Id$
 # =====================================================================
 
-top_dir=$PWD
-bootstrap=`basename $0`
+bootstrap="${PWD}/linux/bootstrap"
 
-set -x
-
-aclocal \
-&& libtoolize --automake --force \
-&& autoheader \
-&& automake --add-missing --foreign \
-&& autoconf
-
-if [ -d source/plugins ]; then
-    cd source/plugins && $top_dir/linux/$bootstrap
+if test ! -f "$bootstrap"; then
+    echo "run ./linux/bootstrap from the top source directory"
+    exit 1
 fi
+
+do_bootstrap()
+{
+    set -x
+    aclocal \
+	&& libtoolize --automake --force \
+	&& autoheader \
+	&& automake --add-missing --foreign \
+	&& autoconf
+    set +x
+}
+
+case "$1" in
+    server|lang)
+	echo "* bootstrapping server/lang"
+	do_bootstrap
+	;;
+    plugins)
+	if test -d source/plugins; then
+	    echo "* bootstrapping plugins"
+	    cd source/plugins && do_bootstrap
+	else
+	    echo "directory source/plugins not found"
+	    exit 1
+	fi
+	;;
+    *)
+	"$bootstrap" server
+	"$bootstrap" plugins
+	;;
+esac
 
 # EOF
